### PR TITLE
Replaced "Know More" link by a question mark icon #116

### PR DESCRIPTION
**Pull request by boro741**
Replaced the Know More with question mark from CarbonFootprintCore.js file

### CODE REVIEW

**Comment by Ceilican** [comment]
Hi @boro741 ! Thank you for your contribution. We wanted to have a [question mark icon](https://www.google.com.au/search?q=question+mark+icon&client=safari&rls=en&source=lnms&tbm=isch&sa=X&ved=0ahUKEwj3vu2c-I3QAhUDupQKHbdyD8wQ_AUICCgB&biw=1280&bih=712), not just the question mark character.

Could you revise your pull request, replacing the question mark character by a nice *green* question mark icon?

**Comment by boro741** [comment]
Yep I'm working so far on that. I just kinda struggling how to make img tag work locally on computer. But I've successfully tested using url links.

**Comment by Ceilican** [comment]
Hi @boro741 ! Yes, it would be better to make the extension access locally stored images than remote URL linked images. I suggest that you have a look where @PrateekGupta1509 stored the images he used in the "Know More" pages and see how he accessed those images, and then do something similar for the question mark icon.

Thanks!

**Comment by boro741** [comment]
Thats ok  how @PrateekGupta1509  used  image in HTML but the problem is it doesn't work the same with innerHTML in Js file.
So I think I'm kinda lack some basic in using innerHTML. So I'm trying to figure out how to make img link work in innerHTML.

So here's snippet:
I've 
Working with link:
`e.innerHTML = '<a href=' + knowMoreUrl + ' target=\'_blank\' title=\'' +
    titleStr + '\' class=\'carbon\' id=\'carbon\'>' +
    this.footprintToString(footprint) +
    '</a> <a class=\'know-more-link\' href=' + knowMoreUrl +
    ' target=\'_blank\' title=\'' + titleStr + '\'>';
  e.onh;`

Not working when path specified locally:
`e.innerHTML = '<a href=' + knowMoreUrl + ' target=\'_blank\' title=\'' +
    titleStr + '\' class=\'carbon\' id=\'carbon\'>' +
    this.footprintToString(footprint) +
    '</a> <a class=\'know-more-link\' href=' + knowMoreUrl +
    ' target=\'_blank\' title=\'' + titleStr + '\'>';
  e.onh;`

Sorry if this question was not supposed to be asked here and the problem need to be figured out by myself. 

By the way thank you @Ceilican for ur kind response.

**Comment by Ceilican** [comment]
Ah, ok. I understand the difficulty now.

This might help:
https://www.google.com.au/search?client=safari&rls=en&q=chrome+extension+how+to+inject+local+images+through+content+script&ie=UTF-8&oe=UTF-8&gfe_rd=cr&ei=yuIgWKSALKbM8gfYxpWADg

**Comment by Ceilican** [comment]
And yes, it is ok to ask technical questions here. It is even better than by email.

**Comment by boro741** [comment]
Hey @Ceilican  I've done replacing html character question mark with question mark icon. 
Checkout my new commit.

**Comment by Ceilican** [comment]
Hi @boro741 ! Great that you managed to solve the issue. Thank you very much! Just two minor things before I can merge your pull request:

1) Have you checked that the icon you chose is free (i.e. not copyrighted)? (You can use Google's advanced search tools to narrow down the image search to free images only.)

2) Your pull request became conflicting and cannot be automatically merged. This usually happens when another developer changed the same file that you did and pushed his changes before you did. To fix this issue, you must first pull all the changes in the main Github repository to your local repository, solve the conflict locally, then push your changes to your own forked Github repository, and finally re-submit the pull request. (That's a common procedure when working with git and github, and there should be easy to find tutorials on how to do this in the internet. If you need help, let us know.)

**Comment by Ceilican** [comment]
Thanks!

**Pull request merged**
